import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/app/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100%] h-[100vh] flex justify-center items-center">
          <div className="max-w-[500px] rounded-[10px]">
            <Nav />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
